[package]
name = "scow-infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.1"
aws-sdk-cloudformation = "0.26.0"
tokio = { version = "1", features = ["full"] }
