[package]
name = "gr-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gr-infra = { path = "../gr-infra" }
tokio = { version = "1", features = ["full"] }
