Parameters:
  BaseImageId:
    Type: String
    # ubuntu 22.04
    Default: ami-007855ac798b5175e
  DevSecurityGroup:
    Type: String
    Default: sg-0ce19ae8f275b3a2b
  DevKeyName:
    Type: String
    Default: gr-dev-instances-1
  PublicSubnetId1:
    Type: String
    Default: subnet-991015fe
  DatalakeBucketName:
    Type: String
    Description: Bucket for raw public data and intermediate results
    Default: gr-datalake
  InfraResourcesBucketName:
    Type: String
    Description: Bucket for raw public data and intermediate results
    Default: gr-infra-resources

Resources:
  DatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DatalakeBucketName
      AccessControl: Private
      Tags:
        - Key: ProjectName
          Value: gooserocket
  InfraResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InfraResourcesBucketName
      AccessControl: Private
      Tags:
        - Key: ProjectName
          Value: gooserocket
  DeveloperIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GrDeveloperIamPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - Fn::GetAtt: DatalakeBucket.Arn
                  - Fn::GetAtt: InfraResourcesBucket.Arn
      Path: /
      Tags:
        - Key: ProjectName
          Value: gooserocket
  DeveloperEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref DeveloperIamRole

Outputs:
  BaseImageId:
    Description: Base image id to be used by all EC2 instances
    Value: !Ref BaseImageId
    Export:
      Name: BaseImageId
  DevSecurityGroup:
    Value: !Ref DevSecurityGroup
    Export:
      Name: DevSecurityGroup
  DevKeyName:
    Value: !Ref DevKeyName
    Export:
      Name: DevKeyName
  PublicSubnetId1:
    Value: !Ref PublicSubnetId1
    Export:
      Name: PublicSubnetId1
  DeveloperEC2InstanceProfileId:
    Value: !Ref DeveloperEC2InstanceProfile
    Export:
      Name: DeveloperEC2InstanceProfileId
