Parameters:
  DevSecurityGroup:
    Type: String
    Default: sg-0ce19ae8f275b3a2b
  DevKeyName:
    Type: String
    Default: gr-dev-instances-1
  PublicSubnetId1:
    Type: String
    Default: subnet-991015fe
  DatalakeBucketName:
    Type: String
    Description: Bucket for raw public data and intermediate results
    Default: gr-datalake
  InfraResourcesBucketName:
    Type: String
    Description: Bucket for raw public data and intermediate results
    Default: gr-infra-resources

Resources:
  DatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DatalakeBucketName
      AccessControl: Private
      Tags:
        - Key: ProjectName
          Value: gooserocket
  InfraResourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InfraResourcesBucketName
      AccessControl: Private
      Tags:
        - Key: ProjectName
          Value: gooserocket
  DeveloperIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GrDeveloperIamPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - Fn::GetAtt: DatalakeBucket.Arn
                  - Fn::GetAtt: InfraResourcesBucket.Arn
      Path: /
      Tags:
        - Key: ProjectName
          Value: gooserocket
  DeveloperEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref DeveloperIamRole
  Ec2ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AWSImageBuilderReadOnlyAccess
      Path: /
      Tags:
        - Key: ProjectName
          Value: gooserocket
  EC2ImageBuilderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref Ec2ImageBuilderRole

  GitCloneGooserocketIBComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: git-clone-gooserocket
      Platform: Linux
      Version: 1.0.0
      SupportedOsVersions:
        - Ubuntu
      Data: |
        name: Git clone gooserocket
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: GitCloneGooserocket
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      git clone https://github.com/eltonlaw/gooserocket.git /home/ubuntu/gooserocket
                      chown -R ubuntu:ubuntu /home/ubuntu/gooserocket

Outputs:
  DevSecurityGroup:
    Value: !Ref DevSecurityGroup
    Export:
      Name: DevSecurityGroup
  DevKeyName:
    Value: !Ref DevKeyName
    Export:
      Name: DevKeyName
  PublicSubnetId1:
    Value: !Ref PublicSubnetId1
    Export:
      Name: PublicSubnetId1
  DeveloperEC2InstanceProfileId:
    Value: !Ref DeveloperEC2InstanceProfile
    Export:
      Name: DeveloperEC2InstanceProfileId
  EC2ImageBuilderInstanceProfileId:
    Value: !Ref EC2ImageBuilderInstanceProfile
    Export:
      Name: EC2ImageBuilderInstanceProfileId
  GitCloneGooserocketIBComponentArn:
    Value: !Ref GitCloneGooserocketIBComponent
    Export:
      Name: GitCloneGooserocketIBComponentArn
