Parameters:
  JupyterInstanceType:
    Type: String
    Description: Instance type to deploy jupyter notebook with
    Default: t2.micro

Resources:
  JupyterEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Fn::ImportValue: DeveloperEC2InstanceProfileId
      InstanceType: !Ref JupyterInstanceType
      ImageId: !ImportValue JupyterImageId
      KeyName:
        Fn::ImportValue: DevKeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId:
            Fn::ImportValue: PublicSubnetId1
          GroupSet:
            - Fn::ImportValue: DevSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          ## Requires reboot because linux kernel updates as well
          # apt upgrade -y
          apt install awscli python3-pip -y
          pip3 install jupyter
          jupyter notebook --generate-config --allow-root
          nohup jupyter notebook \
            --port 8888  \
            --ip='*' \
            --NotebookApp.token='' \
            --NotebookApp.password='' \
            --no-browser </dev/null >/dev/null 2>&1 &
          ## FIXME: creds don't exist yet
          # INSTANCE_ID=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
          # aws ec2 create-tags --resources $INSTANCE_ID --tags Key=App,Value="jupyter-notebook" --region us-east-1
      Tags:
        - Key: ProjectName
          Value: gooserocket
Outputs:
  JupyterEC2InstancePublicIp:
    Value:
      Fn::GetAtt: JupyterEC2Instance.PublicIp
    Export:
      Name: JupyterEC2InstancePublicIp
